import type { ItemDefinition } from "./types";

export const ITEM_CATALOG: ItemDefinition[] = [
  {
    id: "yellow_body",
    name: "Tinta Mel",
    slot: "bodyColor",
    category: "style",
    rarity: "common",
    price: 0,
    tags: ["belas-artes", "corpo"],
    unlockRule: {},
    preview: { icon: "body", accent: "#f4c434" },
    visual: { rarity: "common", badge: "none", frameStyle: "soft", previewVariant: "shine" },
    renderProfile: { family: "color", accent: "#f4c434" }
  },
  {
    id: "charcoal_body",
    name: "Tinta Carvao",
    slot: "bodyColor",
    category: "style",
    rarity: "rare",
    price: 320,
    tags: ["design", "corpo"],
    unlockRule: { minLevel: 4 },
    preview: { icon: "body", accent: "#2f2a25" },
    visual: { rarity: "rare", badge: "meta", frameStyle: "bold", previewVariant: "paper" },
    renderProfile: { family: "color", accent: "#2f2a25" }
  },
  {
    id: "amber_stripes",
    name: "Listras Ocre",
    slot: "stripeColor",
    category: "style",
    rarity: "common",
    price: 0,
    tags: ["belas-artes", "listras"],
    unlockRule: {},
    preview: { icon: "stripes", accent: "#8b5831" },
    visual: { rarity: "common", badge: "none", frameStyle: "soft", previewVariant: "flat" },
    renderProfile: { family: "color", accent: "#8b5831" }
  },
  {
    id: "blue_wings",
    name: "Asas Ciano",
    slot: "wingColor",
    category: "style",
    rarity: "common",
    price: 0,
    tags: ["design", "asas"],
    unlockRule: {},
    preview: { icon: "wings", accent: "#b9eff6" },
    visual: { rarity: "common", badge: "none", frameStyle: "soft", previewVariant: "shine" },
    renderProfile: { family: "color", accent: "#b9eff6" }
  },
  {
    id: "ba_uniform",
    name: "Uniforme Belas Artes",
    slot: "outfit",
    category: "closet",
    rarity: "common",
    price: 160,
    tags: ["belas-artes", "uniforme"],
    unlockRule: { minLevel: 2 },
    preview: { icon: "uniform", accent: "#f4c434" },
    visual: { rarity: "common", badge: "none", frameStyle: "soft", previewVariant: "flat" },
    renderProfile: { family: "outfit", accent: "#f4c434" }
  },
  {
    id: "journalism_vest",
    name: "Colete Jornalismo",
    slot: "outfit",
    category: "closet",
    rarity: "rare",
    price: 220,
    tags: ["jornalismo", "outfit"],
    unlockRule: { minLevel: 3 },
    preview: { icon: "vest", accent: "#2167a8" },
    visual: { rarity: "rare", badge: "meta", frameStyle: "bold", previewVariant: "paper" },
    renderProfile: { family: "outfit", accent: "#2167a8" }
  },
  {
    id: "economy_blazer",
    name: "Blazer Economia",
    slot: "outfit",
    category: "closet",
    rarity: "rare",
    price: 240,
    tags: ["economia", "outfit"],
    unlockRule: { minLevel: 4 },
    preview: { icon: "blazer", accent: "#2f8f63" },
    visual: { rarity: "rare", badge: "meta", frameStyle: "bold", previewVariant: "paper" },
    renderProfile: { family: "outfit", accent: "#2f8f63" }
  },
  {
    id: "pp_blazer",
    name: "Blazer Publicidade",
    slot: "outfit",
    category: "closet",
    rarity: "epic",
    price: 280,
    tags: ["publicidade", "campanha"],
    unlockRule: { minLevel: 5 },
    preview: { icon: "blazer", accent: "#df4d5c" },
    visual: { rarity: "epic", badge: "new", frameStyle: "premium", previewVariant: "shine" },
    renderProfile: { family: "outfit", accent: "#df4d5c" }
  },
  {
    id: "beret",
    name: "Boina de Pintura",
    slot: "hat",
    category: "closet",
    rarity: "common",
    price: 145,
    tags: ["belas-artes", "chapeu"],
    unlockRule: {},
    preview: { icon: "hat", accent: "#7256a6" },
    visual: { rarity: "common", badge: "none", frameStyle: "soft", previewVariant: "flat" },
    renderProfile: { family: "hat", accent: "#7256a6" }
  },
  {
    id: "critique_glasses",
    name: "Oculos de Critica",
    slot: "glasses",
    category: "closet",
    rarity: "rare",
    price: 165,
    tags: ["design", "oculos"],
    unlockRule: { minLevel: 2 },
    preview: { icon: "glasses", accent: "#4b5563" },
    visual: { rarity: "rare", badge: "meta", frameStyle: "bold", previewVariant: "paper" },
    renderProfile: { family: "glasses", accent: "#4b5563" }
  },
  {
    id: "brush_prop",
    name: "Pincel Fino",
    slot: "prop",
    category: "closet",
    rarity: "common",
    price: 0,
    tags: ["belas-artes", "acessorio"],
    unlockRule: {},
    preview: { icon: "prop", accent: "#8b5831" },
    visual: { rarity: "common", badge: "none", frameStyle: "soft", previewVariant: "flat" },
    renderProfile: { family: "prop", accent: "#8b5831" }
  },
  {
    id: "camera_prop",
    name: "Camera de Making Of",
    slot: "prop",
    category: "closet",
    rarity: "rare",
    price: 210,
    tags: ["jornalismo", "acessorio"],
    unlockRule: { minLevel: 3 },
    preview: { icon: "prop", accent: "#34302b" },
    visual: { rarity: "rare", badge: "meta", frameStyle: "bold", previewVariant: "paper" },
    renderProfile: { family: "prop", accent: "#34302b" }
  },
  {
    id: "studio_wall",
    name: "Parede de Atelie",
    slot: "bg",
    category: "home",
    rarity: "common",
    price: 0,
    tags: ["belas-artes", "fundo"],
    unlockRule: {},
    preview: { icon: "bg", accent: "#f1e9dc" },
    visual: { rarity: "common", badge: "none", frameStyle: "soft", previewVariant: "flat" },
    renderProfile: { family: "room", accent: "#f1e9dc" }
  },
  {
    id: "agency_wall",
    name: "Agencia PP",
    slot: "bg",
    category: "home",
    rarity: "epic",
    price: 330,
    tags: ["publicidade", "fundo"],
    unlockRule: { minLevel: 5 },
    preview: { icon: "bg", accent: "#f8dde2" },
    visual: { rarity: "epic", badge: "new", frameStyle: "premium", previewVariant: "shine" },
    renderProfile: { family: "room", accent: "#f8dde2" }
  },
  {
    id: "nectar",
    name: "Nectar do Cafe",
    slot: "food",
    category: "cantina",
    rarity: "common",
    price: 12,
    consumable: true,
    tags: ["consumivel", "fome"],
    unlockRule: {},
    preview: { icon: "food", accent: "#f59e0b" },
    visual: { rarity: "common", badge: "none", frameStyle: "soft", previewVariant: "flat" },
    renderProfile: { family: "face" },
    effect: { hunger: 18, health: 1 }
  },
  {
    id: "rest_tonic",
    name: "Tonico de Descanso",
    slot: "potion",
    category: "care",
    rarity: "rare",
    price: 55,
    consumable: true,
    tags: ["consumivel", "energia"],
    unlockRule: {},
    preview: { icon: "potion", accent: "#38bdf8" },
    visual: { rarity: "rare", badge: "meta", frameStyle: "bold", previewVariant: "shine" },
    renderProfile: { family: "face" },
    effect: { energy: 34 }
  }
];
